#!/bin/bash

find . -name '*.web*' -type f -exec sh -c '
for f; do
   echo "$f"
   application_file="$(basename "$f")"
   if [ "$(echo ${application_file##*.})" = "webpresent" ] || [ "$(echo ${application_file##*.})" = "weborigin" ];
   then
      echo "Valid"
fi
done' sh {} +
# from https://stackoverflow.com/a/9394625/5623661 and https://stackoverflow.com/a/965069/5623661
