#!/bin/bash

find . -name '*.web*.txt' -type f -exec sh -c '
for f; do
   echo "$f"
   if [[ $f == *.txt ]]; then
   echo "Valid webpresent file"
   else
      echo "Not a valid .webpresent.txt nor .weborigin.txt file"
fi
done' sh {} +
# from https://stackoverflow.com/a/9394625/5623661 and https://stackoverflow.com/a/407334/5623661
