#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

function eachwebpresent {
while IFS="" read -r p || [ -n "$p" ]
do
if [[ "$p" == *"drive.google.com"* ]] || ipfs cid validate "$p"
   then
      echo "This is a GoogleDrive or IPFS file!"
      if [[ "$p" == *"$SUB"* ]]; then
         cd "$(dirname "${file}")" && gdown "$p"
         cd "$SCRIPTPATH"
      fi
      if ipfs cid validate "$p"; then
         ipget "$p" -o "$(dirname "${file}")"
      fi
   else
      wget -N "$p" -P "$(dirname "${file}")"
fi
done < "$file"
}

find . -type f -name '*.web*' -print0 | while IFS= read -r -d '' file
do
   echo "Webpresent file found: $file"
   application_file="$(basename "$file")"
   if [ "$(echo ${application_file##*.})" = "webpresent" ] || [ "$(echo ${application_file##*.})" = "weborigin" ];
   then
      eachwebpresent
   else
      echo "Not a valid .webpresent nor .weborigin file"
fi
done
# from https://stackoverflow.com/a/9394625/5623661, https://stackoverflow.com/a/965069/5623661, https://linuxize.com/post/how-to-check-if-string-contains-substring-in-bash/, https://stackoverflow.com/a/6121114/5623661 and https://stackoverflow.com/a/1078539/5623661, https://stackoverflow.com/a/50670037/5623661
