#!/bin/bash

function eachwebpresent {
echo "Valid"
}

find . -type f -name '*.web*' -print0 | while IFS= read -r -d '' file
do
   echo "Webpresent file found: $file"
   echo "$(basename $file)"
   echo "$(basename "$file")"
   application_file="$(basename "$file")"
   echo "$application_file"
   echo ${application_file##*.}
   if [ "$(echo ${application_file##*.})" = "webpresent" ] || [ "$(echo ${application_file##*.})" = "weborigin" ];
   then
      eachwebpresent
   else
      echo "Not a valid .webpresent nor .weborigin file"
fi
done
# from https://stackoverflow.com/a/9394625/5623661, https://stackoverflow.com/a/965069/5623661 and https://linuxize.com/post/how-to-check-if-string-contains-substring-in-bash/
