#!/bin/bash

find . -name '*.web*.txt' -type f -exec sh -c '
for f; do
   echo "$f"
   if [ "${f: -4}" == ".txt" ]; then echo "Valid";fi
done' sh {} +
# from https://stackoverflow.com/a/9394625/5623661 and https://stackoverflow.com/a/407229/5623661
